version: "3.7"

services:
  nginx:
    image: nginx:1.17.8
    volumes:
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web

  web:
    build:
      context: ./docker
    links:
      - pgsql
      - redis
    volumes:
      - .:/var/www
      - ./docker/logs:/var/log/supervisor

  pgsql:
    image: postgres:12.2
    ports:
      - '5432:5432'
    expose:
      - 5432
    volumes:
      - pgsql_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: laravel
      POSTGRES_DB: laravel
      POSTGRES_PASSWORD: secret

  redis:
    image: redis:5.0.7
    expose:
      - 6379
    volumes:
      - redis_data:/data

volumes:
  pgsql_data:
  redis_data:
